<template>
    <div>
        <router-view class="router-parent"></router-view>
        <div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
            <!--begin::Svg Icon | path: icons/duotune/arrows/arr066.svg-->
            <span class="svg-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                    <rect opacity="0.5" x="13" y="6" width="13" height="2" rx="1" transform="rotate(90 13 6)" fill="black" />
                    <path d="M12.5657 8.56569L16.75 12.75C17.1642 13.1642 17.8358 13.1642 18.25 12.75C18.6642 12.3358 18.6642 11.6642 18.25 11.25L12.7071 5.70711C12.3166 5.31658 11.6834 5.31658 11.2929 5.70711L5.75 11.25C5.33579 11.6642 5.33579 12.3358 5.75 12.75C6.16421 13.1642 6.83579 13.1642 7.25 12.75L11.4343 8.56569C11.7467 8.25327 12.2533 8.25327 12.5657 8.56569Z" fill="black" />
                </svg>
            </span>
            <!--end::Svg Icon-->
        </div>
        <div id="page-loading" class="d-flex" v-if="$store.state.pageLoading">
            <div class="loadingio-spinner-blocks-5qo15v8j0al m-auto"><div class="ldio-1tz647etzh6"><div style='left:-3.5px;top:-3.5px;animation-delay:0s'></div><div style='left:32.5px;top:-3.5px;animation-delay:0.125s'></div><div style='left:68.5px;top:-3.5px;animation-delay:0.25s'></div><div style='left:-3.5px;top:32.5px;animation-delay:0.875s'></div><div style='left:68.5px;top:32.5px;animation-delay:0.375s'></div><div style='left:-3.5px;top:68.5px;animation-delay:0.75s'></div><div style='left:32.5px;top:68.5px;animation-delay:0.625s'></div><div style='left:68.5px;top:68.5px;animation-delay:0.5s'></div></div></div>
        </div>
    </div>
</template>

<script>
    export default{
        data(){
            return {

            }
        },
        mounted(){

        }
    }
</script>

<style type="text/css" scoped>
    @keyframes ldio-1tz647etzh6 {
        0% { background: #f8b26a }
        12.5% { background: #f8b26a }
        12.625% { background: #e15b64 }
        100% { background: #e15b64 }
    }
    .ldio-1tz647etzh6 div {
        position: absolute;
        width: 35px;
        height: 35px;
        background: #e15b64;
        animation: ldio-1tz647etzh6 1s linear infinite;
    }
    .loadingio-spinner-blocks-5qo15v8j0al {
        width: 61px;
        height: 61px;
        display: inline-block;
        overflow: hidden;
        background: #ffffff;
    }
    .ldio-1tz647etzh6 {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(0.61);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-1tz647etzh6 div { box-sizing: content-box; }
    /* generated by https://loading.io/ */

    #page-loading{
        /* width:100vw !important;
        height:100vh !important; */
        position:fixed !important;
        display:flex !important;
        top:0 !important;
        bottom:0 !important;
        left:0 !important;
        right:0 !important;
        z-index:99999;
        background-color: rgba(230, 241, 255, 0.611);
    }
</style>
